site_name: Nasjonal arkitektur for et felles digitalt økosystem
site_description: Dokumentasjon generert fra ArchiMate-modell
theme:
  name: material
  logo: images/digdir_logo.svg
  language: nb
  palette:
    primary: indigo
    accent: indigo
markdown_extensions:
  - toc:
      title: "Innhold på denne siden"
      toc_depth: 2-6
nav:
  - Innledning: index.md
  - Dokumentasjon av modell for Nasjonal arkitektur:
    - Innledning: modell.md
    - Interaktiv modell i Archi: interaktiv-modell.md
  - Dypdykk og konsepter:
      - Nasjonal arkitektur som Kunnskapsgraf: kunnskapsgraf-maal.md
  - Oversikt over ressurser i felles økosystem: ressurser.md

extra_javascript:
  - javascripts/custom.js
