site_name: Nasjonal Arkitektur
site_description: Dokumentasjon generert fra ArchiMate-modell
theme:
  name: material
  language: 'no'
  palette:
    primary: indigo
    accent: indigo
nav:
  - Forside: index.md
