site_name: Nasjonal Arkitektur
site_description: Dokumentasjon generert fra ArchiMate-modell
theme:
  name: material
  logo: images/digdir_logo.svg
  language: nb
  palette:
    primary: indigo
    accent: indigo
markdown_extensions:
  - toc:
      title: "Innhold på denne siden"
nav:
  - Forside: index.md
  - Rammeverksmodell for Nasjonal arkitektur: modell.md
